
/**
 * SolarAudit — Energy Engine: Warnings
 *
 * Warning messages generated by the energy calculation engine.
 *
 * Warnings do not invalidate the calculation.
 * They indicate conditions that should receive engineering review.
 */

// -----------------------------------------------------------------------------
// Generation / Consumption
// -----------------------------------------------------------------------------

export const WARN_ZERO_GENERATION =
  "PV generation is zero. Check PV capacity, peak sun hours, and performance ratio.";

export const WARN_ZERO_CONSUMPTION =
  "Energy consumption is zero. Check the load profile and daily consumption.";

// -----------------------------------------------------------------------------
// PV Performance
// -----------------------------------------------------------------------------

export function WARN_LOW_PR(
  performanceRatio: number,
): string {
  return (
    `Low PV performance ratio detected: ` +
    `${(performanceRatio * 100).toFixed(1)}%. ` +
    `Review shading, temperature, soiling, wiring, inverter losses, ` +
    `and other system derating factors.`
  );
}

// -----------------------------------------------------------------------------
// Self-Consumption
// -----------------------------------------------------------------------------

export function WARN_LOW_SELF_CONSUMPTION(
  selfConsumptionRate: number,
): string {
  return (
    `Low PV self-consumption detected: ` +
    `${(selfConsumptionRate * 100).toFixed(1)}%. ` +
    `Consider load shifting, battery storage, or load management.`
  );
}

// -----------------------------------------------------------------------------
// Battery Sizing
// -----------------------------------------------------------------------------

export const WARN_BATTERY_OVERSIZED =
  "Battery usable capacity is significantly larger than daily energy consumption. Review battery sizing and utilization.";

export const WARN_BATTERY_UNDERSIZED =
  "Battery usable capacity is very small relative to daily energy consumption. Review battery sizing and required autonomy.";
